# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-30 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191030_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course_created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 30, 15, 23, 36, 495760, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
