# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
